# Generated by Django 5.2.1 on 2025-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.RenameField(
            model_name='mediafile',
            old_name='update_ad',
            new_name='updated_at',
        ),
    ]
