# Generated by Django 5.2.1 on 2025-06-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
