# Generated by Django 5.2.1 on 2025-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0002_user_is_confirmed'),
        ('products', '0004_alter_commint_product_alter_commint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(related_name='saved_by_users', to='products.product'),
        ),
    ]
