# Generated by Django 5.2.1 on 2025-06-19 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0004_alter_user_options_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 8, 42, 2, 307546, tzinfo=datetime.timezone.utc)),
        ),
    ]
