# Generated by Django 5.2.1 on 2025-06-21 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0005_alter_story_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 11, 34, 6, 251435, tzinfo=datetime.timezone.utc)),
        ),
    ]
