# Generated by Django 5.2.1 on 2025-06-26 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0007_alter_story_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 15, 13, 44, 272918, tzinfo=datetime.timezone.utc)),
        ),
    ]
