# Generated by Django 5.2.1 on 2025-06-28 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accaunts', '0008_rename_update_ad_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 29, 8, 48, 47, 950669, tzinfo=datetime.timezone.utc)),
        ),
    ]
