from .CartItem.CartItemCreate.views import *
from .CartItem.CartItemUpdate.views  import *
from .CartItem.CartItemDelete.views  import *
from .CartItem.CartItemList.views  import *
from .logautsession.views  import *
from .loginsession.views  import * 
from .Profile.PsswordReset.views import *
from .Profile.ProfileDelete.views import *
from .Profile.ProfileUpdate.views import *
from .Profile.Register.views import *
from .SavedList.views import *
from .SaveProduct.views import *
from .Storis.StorisList.views import *
from .Storis.StorisCreate.views import *
from .Storis.StorisUpdate.views import *
from .Storis.StorisDelete.views import *
