# Generated by Django 5.2.1 on 2025-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='update_ad',
            new_name='updated_at',
        ),
    ]
