# Generated by Django 5.2.1 on 2025-06-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description_en_product_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='commint',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='update_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='update_ad',
            new_name='updated_at',
        ),
    ]
